### PR TITLE
Added multiple instance support and removed need for config.h

### PR DESCRIPTION
**Pull request by dmadison**
This has some big changes in it, so here's the rundown.

**The Good:** :smile:

- _Completely eliminates 'config.h'_
- _Allows multiple instances of the Lixie class_ (e.g. multiple sets of Lixies on multiple pins)
- Parameterizes led type and color order (if someone builds a Lixie with other LED-types)

**The Bad:** :disappointed:

- _Uses dynamic memory allocation_
- Currently limited to pins 0-13 (can be expanded!)

As I see it, this is a big improvement over the current implementation that requires users to either tweak the library 'config.h' or set up their own config file. The big disadvantage of course is that the library needs to use dynamic allocation to set the arrays correctly. I don't think this is such a sin because it's done in the constructor and the array lengths are never altered, but it it a sin nonetheless.

I've tested this with a pair of WS2812B strips on two different pins and it works marvelously, though as always I'd encourage you to test on the proper hardware before merging.

### CODE REVIEW

**Comment by connornishijima** [comment]
I'll clone and give it a try! Holy cow!

**Comment by connornishijima** [comment]
Works flawlessly on my end!

    void Lixie::build_controller(uint8_t DataPin){
    	switch (DataPin){
    		case 0:
    			FastLED.addLeds<LED_TYPE, 0, COLOR_ORDER>(leds, NumLEDs);
    			break;
    		case 1:
    			FastLED.addLeds<LED_TYPE, 1, COLOR_ORDER>(leds, NumLEDs);
    			break;
    		case 2:
    			FastLED.addLeds<LED_TYPE, 2, COLOR_ORDER>(leds, NumLEDs);
    			break;
    		case 3:
    			FastLED.addLeds<LED_TYPE, 3, COLOR_ORDER>(leds, NumLEDs);
    			break;

This is clever. This way the DataPin is cheated into a constant, right? I love it. FastLED was super picky about that.

**Comment by dmadison** [comment]
Glad to hear it!

Yup - the data pin is passed in the constructor and the switch statement is evaluated at compile-time. It's a little messy, but it works!

**Comment by connornishijima** [comment]
I'll be posting an update to the Hackaday.io logs soon once the final PCB arrives and shout you out for sure. Once it's arrived and confirmed working I'll go ahead and order the medium run of boards, and 32 units worth of laser cutting. All the LEDs, caps, and bolt hardware are already here. :) For the awesome contributions, I'll only put 26 units in stock, and save 6 for you to make sure you get a chance to order from the first batch! I'll only charge for 4. Thanks again, David!

**Comment by dmadison** [comment]
Wow! I really appreciate the gesture, but I don't have the money to spend right now 😞. Throwing it away on too many other projects, haha!

**Comment by connornishijima** [comment]
Okay, no worries. :) Offer still stands, just let me know if you ever go to buy!

**Pull request merged**
