### PR TITLE
'write' improvements, input checks, new debug function, bug fixes, and more

### PR DESCRIPTION
**Pull request by dmadison**
Last **big** pull request, promise! Need to get back to work on my own projects.

Changes:

- **Fixed 'get_size' bug**: 
Previously the function would report that any input of '0' had a size of 0. Because the '0' digit still requires one display, the function will now return 1 by default and is bounded to 9 rather than 0.

- **Cleaned 'push_digit' function**:
I added comments to make the function a bit less obscure, and I removed the redundant 'clear' call because the led_states for the first digit needs to be cleared regardless.

- **Added input checks to digit write functions**:
The lower-level 'write_digit' and 'push_digit' functions now have input sanitization. This should prevent accidentally reading and writing outside of allocated memory.

- **Removed overloaded versions of the 'write' function**:
These were actually causing more problems than anything else. Because *almost* everything was defined, a fringe case (uint16_t) was causing compiler issues. A number of these overloaded functions were redundant (uint8_t, byte, int, and long are all encapsulated in uint32_t with no type conversion at all), and the floats are automatically converted to uint32_t by the compiler. Removing all of the excess functions makes the library smaller and less complex, and fixes the compiler issue.
   
   It may make sense to add the float function(s) back in the future with a function to save the digits past the decimal, but that's a separate discussion.

- **Rewrote the uint32_t version of the 'write' function to use integer math**:
This is what I was originally working on before I got carried away. Previously the integer version of the 'write' function used a temporary character array and sprintf. I rewrote the function to work with pure integer math, which improves performance by ~10% on my setup (ignoring push_digit). It also uses less memory.

- **Added 'print_current' debug function**:
While I was messing with rewriting the 'write' functions, I thought it would be useful to have a function that returned the current values of the displays, based on the led_states array. This function prints values as integers to the serial monitor in the same order they are inputted (i.e. opposite of the data order sent to the Lixies), and requires the Serial class be initialized.

- **Changed 'maxed_out' function to use integer math**:
I was struggling with the inaccuracy of Arduino's floats when I was rewriting the 'write' function, so I thought it was best to get rid of them here as well. The function now takes an integer rather than a float and does the calculation using the 'get_size' function. I also flipped the output, so if the value *does* 'max out' the displays the function will return *true*, rather than false.

- **Reorganized header function order**:
This is an aesthetic change, but I moved around some of the functions in the header file to make a more logical order. Like functions are grouped, with more important functions higher in the list.

- **Updated documentation**:
Along with all of the other changes in this pull request, I updated the keywords.txt, README.md, and changelog.md.

   The keywords list was reorganized to match the header file, and I also added a few missing function keywords to the list. The README was updated with all of the new functions that have been added in the past few weeks and the 'uint32_t' datatypes were renamed as 'int' for comprehension purposes. I also changed the wording from "Additional Functions" to "*Advanced* Functions", and added another section for "Debug Functions".

As always -- all of these changes work on my end, but please check a clone against the actual hardware to make sure it works as-intended.

### CODE REVIEW

**Comment by connornishijima** [comment]
This works wonderfully on my end, thanks again for all your work Dave! You've taken a sloppy prototype into production-value code. :) I'm still wrapping my head around C++ libraries.

Let me re-explain a deal for you - I originally offered 6 Lixies for the price of 4 - but how about this: *I'll just give you the two free for your time.* :) "Same difference", no cost to you. You should see your code on the real displays! Email me your shipping address sometime, and I'll just send you 2 units from the first batch. (connornishijima@gmail.com)

**Comment by connornishijima** [comment]
**However - I just hit a snag. The changes made since the build_controller() commits have broken all ESP8266 support it seems. I went to port all ESP8266 examples, and I get this upon including Lixie:**

Compiling libraries...
Compiling library "Lixie"
"C:\Users\XFINITY\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\XFINITY\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0/tools/sdk/include" "-IC:\Users\XFINITY\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0/tools/sdk/lwip/include" "-IC:\Users\XFINITY\AppData\Local\Temp\arduino_build_409534/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10613 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP12"  -DESP8266 "-IC:\Users\XFINITY\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" "-IC:\Users\XFINITY\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\variants\adafruit" "-IC:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src" "-IC:\Users\XFINITY\Documents\Arduino\libraries\FastLED" "C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.cpp" -o "C:\Users\XFINITY\AppData\Local\Temp\arduino_build_409534\libraries\Lixie\Lixie.cpp.o"
In file included from C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.h:11:0,

                 from C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.cpp:7:

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:17:21: note: #pragma message: FastLED version 3.001.001

 #    pragma message "FastLED version 3.001.001"

                     ^

In file included from C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:65:0,

                 from C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.h:11,

                 from C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.cpp:7:

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.cpp:12:40: error: 'static' may not be used when defining (as opposed to declaring) a static data member [-fpermissive]

 static constexpr byte Lixie::addresses[];

                                        ^

In file included from C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:48:0,

                 from C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.h:11,

                 from C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.cpp:7:

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h: In instantiation of 'class FastPin<6u>':

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<6, 20, 50, 30, (EOrder)66u, 0, false, 5>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/chipsets.h:461:7:   required from 'class WS2812Controller800Khz<6u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:102:52:   required from 'class WS2812B<6u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:288:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2812B; unsigned char DATA_PIN = 6u; EOrder RGB_ORDER = (EOrder)66u]'

C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.cpp:267:73:   required from here

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h:206:2: error: static assertion failed: Invalid pin specified

  static_assert(validpin(), "Invalid pin specified");

  ^

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h: In instantiation of 'class FastPin<7u>':

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<7, 20, 50, 30, (EOrder)66u, 0, false, 5>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/chipsets.h:461:7:   required from 'class WS2812Controller800Khz<7u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:102:52:   required from 'class WS2812B<7u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:288:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2812B; unsigned char DATA_PIN = 7u; EOrder RGB_ORDER = (EOrder)66u]'

C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.cpp:270:73:   required from here

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h:206:2: error: static assertion failed: Invalid pin specified

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h: In instantiation of 'class FastPin<8u>':

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<8, 20, 50, 30, (EOrder)66u, 0, false, 5>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/chipsets.h:461:7:   required from 'class WS2812Controller800Khz<8u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:102:52:   required from 'class WS2812B<8u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:288:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2812B; unsigned char DATA_PIN = 8u; EOrder RGB_ORDER = (EOrder)66u]'

C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.cpp:273:73:   required from here

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h:206:2: error: static assertion failed: Invalid pin specified

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h: In instantiation of 'class FastPin<9u>':

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<9, 20, 50, 30, (EOrder)66u, 0, false, 5>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/chipsets.h:461:7:   required from 'class WS2812Controller800Khz<9u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:102:52:   required from 'class WS2812B<9u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:288:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2812B; unsigned char DATA_PIN = 9u; EOrder RGB_ORDER = (EOrder)66u]'

C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.cpp:276:73:   required from here

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h:206:2: error: static assertion failed: Invalid pin specified

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h: In instantiation of 'class FastPin<10u>':

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<10, 20, 50, 30, (EOrder)66u, 0, false, 5>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/chipsets.h:461:7:   required from 'class WS2812Controller800Khz<10u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:102:52:   required from 'class WS2812B<10u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:288:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2812B; unsigned char DATA_PIN = 10u; EOrder RGB_ORDER = (EOrder)66u]'

C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.cpp:279:74:   required from here

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h:206:2: error: static assertion failed: Invalid pin specified

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h: In instantiation of 'class FastPin<11u>':

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<11, 20, 50, 30, (EOrder)66u, 0, false, 5>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/chipsets.h:461:7:   required from 'class WS2812Controller800Khz<11u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:102:52:   required from 'class WS2812B<11u, (EOrder)66u>'

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/FastLED.h:288:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2812B; unsigned char DATA_PIN = 11u; EOrder RGB_ORDER = (EOrder)66u]'

C:\Users\XFINITY\Documents\Arduino\libraries\Lixie\src\Lixie.cpp:282:74:   required from here

C:\Users\XFINITY\Documents\Arduino\libraries\FastLED/fastpin.h:206:2: error: static assertion failed: Invalid pin specified

Using library Lixie at version 1.1.1 in folder: C:\Users\XFINITY\Documents\Arduino\libraries\Lixie 
Using library FastLED at version 3.1.1 in folder: C:\Users\XFINITY\Documents\Arduino\libraries\FastLED 
exit status 1
Error compiling for board Adafruit HUZZAH ESP8266.

**Any ideas what's happening here? I haven't updated Arduino or the ESP8266 board definitions since beginning this library. I've torn everything out on my end to try to fix the issues, but no matter what I do, this "invalid pin" issue persists. FastLED is up to date, and the built in demos work fine on the ESP. :(**

**Comment by connornishijima** [comment]
I've made some progress. ESP8266 won't let constexpr byte Lixie::addresses[] be declared as static in the .cpp, only the header file. Hmm. Doesn't seem to affect anything by changing this, despite whether or not I should. However, the issues seem to come out of the build_controller() switch trick. If I change:

    Lixie::Lixie(uint8_t pin, uint8_t nDigits):NumDigits(nDigits), NumLEDs(nDigits * 20){
    	leds = new CRGB[NumLEDs];
    	led_states = new byte[NumDigits * 3]; // 24 bits for 20 LED states
    	colors = new CRGB[NumDigits];
    	colors_off = new CRGB[NumDigits];
  
    	build_controller(pin);
    }

To:

    Lixie::Lixie(uint8_t pin, uint8_t nDigits):NumDigits(nDigits), NumLEDs(nDigits * 20){
    	leds = new CRGB[NumLEDs];
    	led_states = new byte[NumDigits * 3]; // 24 bits for 20 LED states
    	colors = new CRGB[NumDigits];
    	colors_off = new CRGB[NumDigits];
  
    	controller = &FastLED.addLeds<LED_TYPE, 13, COLOR_ORDER>(leds, NumLEDs);
    }

It will compile and work flawlessly. I'll keep toying with it to see what I can do to use the switch/case technique.

**Comment by connornishijima** [comment]
Okay, it's working. Whew! It turns out, ESP8266 simply won't compile if FastLED tries to use pins 1, 3, 5, 6, 7, 8, 9, 10 or 11. I've added an architecture-specific version of build_controller(), which allows all Arduino pins, and only 0, 2, 4, 12, and 13 on ESP architectures. I'll keep looking into this to see why this is, but for now it's fully compatible with existing code again. :)

Also wouldn't work with switch/case, it would give the extremely vague error of:

    .elf section `.text' will not fit in region `iram1_0_seg'

Once switched to if/else logic, it worked. What the hell? Oh well.

**Comment by connornishijima** [comment]
By the way, here's an ego-boost:

Lixie, before your contributions:
**183 FPS with ESP8266 @ 160MHz with 4 digits**

Lixie, right now:
**377 FPS with ESP8266 @ 160MHz with 4 digits**

Okay, I'm done blowing up your inbox, sorry!

**Comment by dmadison** [comment]
Yikes! That looks like a mess. Glad you were able to sort it out! Out of curiosity, does the ESP8266 code compile if the switch case still exists under the AVR macro?

I'll be sure to take you up on that offer as well! That's very generous. I'll send you an email.

> By the way, here's an ego-boost:
> 
> Lixie, before your contributions:
> 183 FPS with ESP8266 @ 160MHz with 4 digits
> 
> Lixie, right now:
> 377 FPS with ESP8266 @ 160MHz with 4 digits

That's awesome!!

**Comment by dmadison** [comment]
Following-up since we last spoke: did you receive my email? I haven't heard back from you.

**Comment by connornishijima** [comment]
Sorry for the delay! I've verified your account push you did, and I'll be
sending two Lixies soon! I only have four of the release version on hand,
so I need them for a video first. About this time next week I'll ship and
send you the tracking number! :) I mentioned you in the latest Hackaday.io
update:

https://hackaday.io/project/18633-lixie-an-led-alternative-to-the-nixie-tube/log/51733-here-is-the-final-lixie

**Comment by dmadison** [comment]
No worries! Just wanted to make sure it didn't get trapped in your spam filter.

Thanks so much for the mention on the hackaday post as well! The new Lixies look great. You should turn that close-up video into a gif!

**Pull request merged**
